import Footer from '@/Components/Footer/Footer'
import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import AuthProviders from '@/providers/AuthProviders'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme='light'>
      <body className={inter.className}>
        {/* 
        Navbar Start======================================  
        */}
      <div className="navbar bg-base-100">
        <div className="navbar-start">
          <div className="dropdown">
            <label tabIndex={0} className="btn btn-ghost lg:hidden">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h8m-8 6h16" /></svg>
            </label>
            <ul tabIndex={0} className="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
              <li><a>Home</a></li>
              <li>
                <a>Parent</a>
                <ul className="p-2">
                  <li><a>Submenu 1</a></li>
                  <li><a>Submenu 2</a></li>
                </ul>
              </li>
              <li><a>Contact</a></li>
            </ul>
          </div>
          <a className="btn btn-ghost normal-case text-xl">Rental Ride</a>
        </div>
        <div className="navbar-center hidden lg:flex">
          <ul className="menu menu-horizontal px-1">
          <li><Link href="/">Home</Link></li>
            <li tabIndex={0}>
              <details>
                <summary>Bikes</summary>
                <ul className="p-2">
                  <li><a>Bikes</a></li>
                  <li><a>Bikes Details</a></li>
                </ul>
              </details>
            </li>
            <li><Link href="aboutUs">About Us</Link></li>
            <li><Link href="contact">Contact</Link></li>
            <li><Link href="/login">Login</Link></li>
          </ul>
        </div>
        <div className="navbar-end">
          <a className="btn rounded-full bg-primary hover:bg-primaryLight font-bold text-white capitalize">Book Now</a>
        </div>
      </div>
      {/* 
      Navbar End
      */}
    
        <AuthProviders>{children}</AuthProviders>
        <Footer />
      </body>
    </html>
  )
}
